# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Prima mea pagina web 
email: https://www.facebook.com/adi.pascaru
description: > # this means to ignore newlines until "baseurl:"
  Sunt elev la liceul Petru Rares din Suceava
baseurl: "" # the subpath of your site, e.g. /blog
url: "adipascaru.github.io" # the base hostname & protocol for your site
twitter_username: adipascaru
github_username:  adipascaru

# Build settings
markdown: kramdown
